project:
  type: website
  output-dir: docs

website:
  title: "Strategic Conservation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - cv.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/AldridgeCalebA
      - icon: github
        # menu:
          # - text: Source Code
          #   url:  https://code.com
          # - text: Report a Bug
          #   url:  https://bugs.com
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

