---
title: "About"
bibliography: references.bib
---

This page documents my current role, professional journey, areas of expertise, and research interests. 

## Current Role
I am currently employed as a Biologist and Coordinator by the U.S. Fish and Wildlife Service in the Lower Mississippi River Fish and Wildlife Conservation Office in Tupelo, Mississippi. Since I first joined USFWS 2021, my primary responsibility has been leading initiatives to prevent, control, and manage invasive carp populations in the Lower Mississippi River and the Arkansas--Red--White Rivers Sub-basins (include 9 states). Through these efforts, I unite state, federal, academic, and industry partners, steering collaborative approaches to address this conservation challenge.

## Professional Journey
Before joining the Service, my journey was shaped by my academic, professional, and research endeavors. My first "real world" experience was an internship at Freedom Hills Wildlife Management Area near Cherokee, Alabama. There I learned the basics of practical wildlife and fisheries management and gained a broad set of field and labor skills. After that experience I knew I wanted to go back to school but was not sure I could hack it. I took a few courses and worked as a technician at Alabama A&M University in Huntsville for two semesters while searching for a graduate assistantship to support a full time post-graduate education. After several applications, emails, calls, and interviews I found the right opportunity for me at the University of Mississippi. I began my studies in 2014, conducting my Masters thesis on the effects of roads on the abundance and composition streamside salamanders.

After a few years at Ole Miss, I and my wife moved south to work at Mississippi State University. From 2016 to 2018, I worked as a Research Associate in Dr. Beth Baker's R.E.A.C.H. lab. The project I managed while there was focused on innovative strategies to reduce nutrient and sediment loss in agricultural systems through the application of cover crops. This demostration project helped reduce downstream impacts of sedimentation and nutrient runoff and helped me develop as a scientist and manager especially on how to address complex environmental issues through research and practical solutions.

In 2018, I again went back to school for more education, though this time it was more about the project than it was the credintials. I began working as a Graduate Research Assistant in the Mississippi Cooperative Fish and Wildlife Research Unit and pursuing my Ph.D. under the direction of Dr. Michael Colvin (now with U.S. Geological Survey, Columbia Environmental Research Center). In short, my dissertation examined aspects of fisheries governance, monitoring, and management. The center-piece of my dissertation was a prototype framework and set of quantitative tools for linking common agency management objectives to actions and monitoring for formal learning (i.e., Bayesian updating) to efficiently reduce uncertainties and maximize management effectiveness. 

## Areas of Expertise
My approach to conservation is deeply rooted in participatory decision-making, ensuring all stakeholders have a voice in understanding and tackling conservation challenges. I adeptly facilitate discussions to properly frame problems, clarify objectives, identify available actions and strategies, and develop models to encapsulate current ecological understanding and societal values (i.e., Structured Decision Making). Furthermore, my analytical skills---including population modeling, systems analysis, trade-off analysis, and optimization---help me support managers decision-making processes and provide a solid foundation for effective conservation strategies.

## Resaerch Interests
My research interests are broad and driven by stakeholders. In short, I like to problem solve. In alignment with decision-analytic principles, there are four "categories" for my research interests.
- Measuring System States: Optimization of sampling protocols to improve effectiveness and efficiency of measuring system status and improving hypothesis-driven field studies.
- Relating Human Values and System States: Incorporation of social science and human dimensions into natural resource decision-making, including development and evaluation of novel valuation techniques and organizational studies to improve organizational decision quality.
- Finding Optimal Solutions and Decision Support: Development of decision and planning support frameworks and tools for natural resource management and species conservation in order to evaluate tradeoffs among alternative actions, prioritize research activities, and incorporate formal learning into monitoring programs.
- Hypothesis Testing and Adaptive Management: Ecology and conservation science of aquatic ecosystems focusing on population status and dynamics and assemblage responses to perturbations (e.g., invasive species and changes in precipitation patterns) and management (e.g., flood control, habitat enhancement, and harvest controls). 